MethodLength:
  Max: 60

LineLength:
  Max: 120

HashSyntax:
  Enabled: false

# Prefer single-quotes
StringLiterals:
  Enabled: false

AlignParameters:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

Encoding:
  Enabled: false

PercentR:
  Enbled: false

SpaceAroundBraces:
  Enabled: false

FavorPercentR:
  Enabled: false

AndOr:
  Enabled: false

EmptyLineBetweenDefs:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

SymbolName:
  Enabled: false

ReduceArguments:
  Enabled: false
